.TH knxm_release 1 

.SH NAME
afm \- pdf2sty

.SH SYNOPSIS
.\" usage
.B afm
[
.I pdffile
|
.I jsonfile
]



.SH DESCRIPTION
.I afm
is a small program which help to make LaTeX style files of application form
from orginal pdf file of application form.
 


.SH AUTHORS
NUMATA, Yacehide (nu+y at math sci hokudai ac jp)
